language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "Filippo Calabrese"
    token:
      secure: "filippocalabrese-github"
jdk:
  - oraclejdk8
script:
  - mvn -f pom.xml clean verify -Pjacoco coveralls:report
cache:
  directories:
    - '$HOME/.m2/'
